name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] Short description of the feature"
labels: [pending triage]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: "A clear and concise description of what the problem is e.g. I'm always frustrated when... If you found another feature request or bug report related to this issue on GitHub, please mention its number e.g. #7890"
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: checkboxes
    id: do-the-work
    attributes:
      label: "Who shall do the work?"
      options:
        - label: I will do it, I want to contribute
        - label: I am asking for someone else to please do the work
  - type: markdown
    attributes:
      value: |
        ## Additional information (optional)
  - type: input
    id: deadline
    attributes:
      label: Timeline
      description: "Is there a deadline attached to this request? If so, please briefly describe why and provide a date (YYYY-MM-DD)"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here. Here you can add screen shots and / or attach documents for changes to content.
