module.exports = {
	fr: {
		aboutGovernment: "Au sujet du gouvernement",
		contactUs: "Contactez-nous",
		contactUsURL: "//www.canada.ca/fr/contact.html",
		departmentsAndAgencies: "Ministères et organismes",
		departmentsAndAgenciesURL: "//www.canada.ca/fr/gouvernement/min.html",
		publicServiceAndMilitary: "Fonction publique et force militaire",
		publicServiceAndMilitaryURL: "//www.canada.ca/fr/gouvernement/fonctionpublique.html",
		news: "Nouvelles",
		newsURL: "//www.canada.ca/fr/nouvelles.html",
		treatiesLawsAndRegulations: "Traités, lois et règlements",
		treatiesLawsAndRegulationsURL: "//www.canada.ca/fr/gouvernement/systeme/lois.html",
		governmentWideReporting: "Rapports à l'échelle du gouvernement",
		governmentWideReportingURL: "//www.canada.ca/fr/transparence/rapports.html",
		primeMinister: "Premier ministre",
		primeMinisterURL: "https://pm.gc.ca/fra",
		howGovernmentWorks: "Comment le gouvernement fonctionne",
		howGovernmentWorksURL: "//www.canada.ca/fr/gouvernement/systeme.html",
		openGovernment: "Gouvernement ouvert",
		openGovernmentURL: "https://ouvert.canada.ca/",
		aboutThisSite: "À propos de ce site",
		topOfPage: "aut de la page",
		symbolOfTheGovernmentOfCanada: "Symbole du gouvernement du Canada",
		socialMedia: "Médias sociaux",
		socialMediaURL: "//www.canada.ca/fr/sociaux.html",
		mobileApplications: "Applications mobiles",
		mobileApplicationsURL: "//www.canada.ca/fr/mobile.html",
		aboutCanadaCa: "À propos de Canada.ca",
		aboutCanadaCaURL: "https://www1.canada.ca/fr/nouveausite.html",
		termsAndConditions: "Avis",
		termsAndConditionsURL: "//www.canada.ca/fr/transparence/avis.html",
		privacy: "Confidentialité",
		privacyURL: "//www.canada.ca/fr/transparence/confidentialite.html"
	},
	en: {
		aboutGovernment: "About government",
		contactUs: "Contact us",
		contactUsURL: "//www.canada.ca/en/contact.html",
		departmentsAndAgencies: "Departments and agencies",
		departmentsAndAgenciesURL: "//www.canada.ca/en/government/dept.html",
		publicServiceAndMilitary: "Public service and military",
		publicServiceAndMilitaryURL: "//www.canada.ca/en/government/publicservice.html",
		news: "News",
		newsURL: "//www.canada.ca/en/news.html",
		treatiesLawsAndRegulations: "Treaties, laws and regulations",
		treatiesLawsAndRegulationsURL: "//www.canada.ca/en/government/system/laws.html",
		governmentWideReporting: "Government-wide reporting",
		governmentWideReportingURL: "//www.canada.ca/en/transparency/reporting.html",
		primeMinister: "Prime Minister",
		primeMinisterURL: "https://pm.gc.ca/eng",
		howGovernmentWorks: "How government works",
		howGovernmentWorksURL: "//www.canada.ca/en/government/system.html",
		openGovernment: "Open government",
		openGovernmentURL: "https://open.canada.ca/en/",
		aboutThisSite: "About this site",
		topOfPage: "Top of page",
		symbolOfTheGovernmentOfCanada: "Symbol of the Government of Canada",
		socialMedia: "Social media",
		socialMediaURL: "//www.canada.ca/en/social.html",
		mobileApplications: "Mobile applications",
		mobileApplicationsURL: "//www.canada.ca/en/mobile.html",
		aboutCanadaCa: "About Canada.ca",
		aboutCanadaCaURL: "https://www1.canada.ca/en/newsite.html",
		termsAndConditions: "Terms and conditions",
		termsAndConditionsURL: "//www.canada.ca/en/transparency/terms.html",
		privacy: "Privacy",
		privacyURL: "//www.canada.ca/en/transparency/privacy.html"
	}
};