module.exports = {
	fr: {
		allContacts: "Toutes les coordonnées",
		allContactsLink: "https://www.canada.ca/fr/contact.html",
		contextualHeader: "Boîte à outils de l'accessibilité numérique",
		contextualLink1: "",
		contextualLink2: "https://a11y.canada.ca/fr/about/organizations/",
		contextualLink3: "",
		contextualLinkText1: "Contacter la Boîte à outils de l'accessibilité numérique",
		contextualLinkText2: "Accessibilité au gouvernement du Canada",
		contextualLinkText3: "Accessibilité par rôle",
		governmentOfCanadan : "Gouvernement du Canada",
		departmentsAndAgencies: "Ministères et organismes",
		departmentsAndAgenciesURL: "https://www.canada.ca/fr/gouvernement/min.html",
		aboutGovernment: "À propos du gouvernement",
		aboutGovernmentURL: "https://www.canada.ca/fr/gouvernement/systeme.html",
		themesAndTopics: "Thèmes et sujets",
		jobsURL: "https://www.canada.ca/fr/services/emplois.html",
		jobs: "Emplois",
		immigrationURL: "https://www.canada.ca/fr/services/immigration-citoyennete.html",
		immigration: "Immigration et citoyenneté",
		travelURL:"https://voyage.gc.ca/",
		travel: "Voyage et tourisme",
		businessURL: "https://www.canada.ca/fr/services/entreprises.html",
		business: "Entreprises",
		benefitsURL: "https://www.canada.ca/fr/services/prestations.html",
		benefits: "Prestations",
		healthURL: "https://www.canada.ca/fr/services/sante.html",
		health: "Santé",
		taxesURL: "https://www.canada.ca/fr/services/impots.html",
		taxes: "Impôts",
		environmentURL: "https://www.canada.ca/fr/services/environnement.html",
		environment: "Environnement et ressources naturelles",
		defenceURL: "https://www.canada.ca/fr/services/defense.html",
		defence: "Sécurité nationale et défense",
		cultureURL: "https://www.canada.ca/fr/services/culture.html",
		culture: "Culture, histoire et sport",
		policingURL: "https://www.canada.ca/fr/services/police.html",
		policing: "Services de police, justice et urgences",
		transportURL: "https://www.canada.ca/fr/services/transport.html",
		transport: "Transport et infrastructure",
		internationalURL: "https://www.international.gc.ca/world-monde/index.aspx?lang=fra",
		international: "Le Canada et le monde",
		financeURL: "https://www.canada.ca/fr/services/finance.html",
		finance: "Argent et finance",
		scienceURL: "https://www.canada.ca/fr/services/science.html",
		science: "Science et innovation",
		indigenousURL: "https://www.canada.ca/fr/services/autochtones.html",
		indigenous: "Autochtones",
		veteransURL: "https://www.canada.ca/fr/services/veterans-militaire.html",
		veterans: "Vétérans et militaires",
		youthURL: "https://www.canada.ca/fr/services/jeunesse.html",
		youth: "Jeunesse",
		governmentCorporateHeading: "Organisation du gouvernement du Canada",
		socialURL: "https://www.canada.ca/fr/sociaux.html",
		social: "Médias sociaux",
		mobileURL: "https://www.canada.ca/fr/mobile.html",
		mobile: "Applications mobiles",
		aboutURL: "https://www.canada.ca/fr/gouvernement/a-propos.html",
		about: "À propos de Canada.ca",
		termsURL: "https://www.canada.ca/fr/transparence/avis.html",
		terms: "Avis",
		privacyURL: "https://www.canada.ca/fr/transparence/confidentialite.html",
		privacy: "Confidentialité",
		aboutThisSite: "À propos de ce site",
	},
	en: {
		contextualHeader: "Digital Accessibility Toolkit",
		contextualLink1: "",
		contextualLink2: "https://a11y.canada.ca/en/about/organizations/",
		contextualLink3: "",
		contextualLinkText1: "Contact the Digital Accessibility Toolkit",
		contextualLinkText2: "Accessibility in Government of Canada",
		contextualLinkText3: "Accessibility in your role",
		governmentOfCanadan : "Government of Canada",
		allContacts: "All contacts",
		allContactsLink: "https://www.canada.ca/en/contact.html",
		departmentsAndAgencies: "Departments and agencies",
		departmentsAndAgenciesURL: "https://www.canada.ca/en/government/dept.html",
		aboutGovernment: "About government",
		aboutGovernmentURL: "https://www.canada.ca/en/government/system.html",
		themesAndTopics: "Themes and topics",
		jobsURL: "https://www.canada.ca/en/services/jobs.html",
		jobs: "Jobs",
		immigrationURL: "https://www.canada.ca/en/services/immigration-citizenship.html",
		immigration: "Immigration and citizenship",
		travelURL:"https://travel.gc.ca/",
		travel: "Travel and tourism",
		businessURL: "https://www.canada.ca/en/services/business.html",
		business: "Business",
		benefitsURL: "https://www.canada.ca/en/services/benefits.html",
		benefits: "Benefits",
		healthURL: "https://www.canada.ca/en/services/health.html",
		health: "Health",
		taxesURL: "https://www.canada.ca/en/services/taxes.html",
		taxes: "Taxes",
		environmentURL: "https://www.canada.ca/en/services/environment.html",
		environment: "Environment and natural resources",
		defenceURL: "https://www.canada.ca/en/services/defence.html",
		defence: "National security and defence",
		cultureURL: "https://www.canada.ca/en/services/culture.html",
		culture: "Culture, history and sport",
		policingURL: "https://www.canada.ca/en/services/policing.html",
		policing: "Policing, justice and emergencies",
		transportURL: "https://www.canada.ca/en/services/transport.html",
		transport: "Transport and infrastructure",
		internationalURL: "https://international.gc.ca/world-monde/index.aspx?lang=eng",
		international: "Canada and the world",
		financeURL: "https://www.canada.ca/en/services/finance.html",
		finance: "Money and finance",
		scienceURL: "https://www.canada.ca/en/services/science.html",
		science: "Science and innovation",
		indigenousURL: "https://www.canada.ca/en/services/indigenous-peoples.html",
		indigenous: "Indigenous peoples",
		veteransURL: "https://www.canada.ca/en/services/veterans-military.html",
		veterans: "Veterans and military",
		youthURL: "https://www.canada.ca/en/services/youth.html",
		youth: "Youth",
		governmentCorporateHeading: "Government of Canada Corporate",
		socialURL: "https://www.canada.ca/en/social.html",
		social: "Social media",
		mobileURL: "https://www.canada.ca/en/mobile.html",
		mobile: "Mobile applications",
		aboutURL: "https://www.canada.ca/en/government/about.html",
		about: "About Canada.ca",
		termsURL: "https://www.canada.ca/en/transparency/terms.htm",
		terms: "Terms and conditions",
		privacyURL: "https://www.canada.ca/en/transparency/privacy.html",
		privacy: "Privacy",
		aboutThisSite: "About this site",
	}
};
