module.exports = {
	fr: {
		Aboutgovernment: "Au sujet du gouvernement",
		Contactus: "Contactez-nous",
		ContactusURL: "https://www.canada.ca/fr/contact.html",
		Departmentsandagencies: "Ministères et organismes",
		DepartmentsandagenciesURL: "https://www.canada.ca/fr/gouvernement/min.html",
		Publicserviceandmilitary: "Fonction publique et force militaire",
		PublicserviceandmilitaryURL: "https://www.canada.ca/fr/gouvernement/fonctionpublique.html",
		News: "Nouvelles",
		NewsURL: "https://www.canada.ca/fr/nouvelles.html",
		Treatieslawsandregulations: "Traités, lois et règlements",
		TreatieslawsandregulationsURL: "https://www.canada.ca/fr/gouvernement/systeme/lois.html",
		Governmentwidereporting: "Rapports à l'échelle du gouvernement",
		GovernmentwidereportingURL: "https://www.canada.ca/fr/transparence/rapports.html",
		PrimeMinister: "Premier ministre",
		PrimeMinisterURL: "https://pm.gc.ca/fra",
		Howgovernmentworks: "Comment le gouvernement fonctionne",
		HowgovernmentworksURL: "https://www.canada.ca/fr/gouvernement/systeme.html",
		Opengovernment: "Gouvernement ouvert",
		OpengovernmentURL: "https://ouvert.canada.ca/",
		Aboutthissite: "À propos de ce site",
		Topofpage: "aut de la page",
		SymboloftheGovernmentofCanada: "Symbole du gouvernement du Canada",
		Socialmedia: "Médias sociaux",
		SocialmediaURL: "https://www.canada.ca/fr/sociaux.html",
		Mobileapplications: "Applications mobiles",
		MobileapplicationsURL: "https://www.canada.ca/fr/mobile.html",
		AboutCanadaca: "À propos de Canada.ca",
		AboutCanadacaURL: "https://www1.canada.ca/fr/nouveausite.html",
		Termsandconditions: "Avis",
		TermsandconditionsURL: "https://www.canada.ca/fr/transparence/avis.html",
		Privacy: "Confidentialité",
		PrivacyURL: "https://www.canada.ca/fr/transparence/confidentialite.html"
	},
	en: {
		Aboutgovernment: "About government",
		Contactus: "Contact us",
		ContactusURL: "https://www.canada.ca/en/contact.html",
		Departmentsandagencies: "Departments and agencies",
		DepartmentsandagenciesURL: "https://www.canada.ca/en/government/dept.html",
		Publicserviceandmilitary: "Public service and military",
		PublicserviceandmilitaryURL: "https://www.canada.ca/en/government/publicservice.html",
		News: "News",
		NewsURL: "https://www.canada.ca/en/news.html",
		Treatieslawsandregulations: "Treaties, laws and regulations",
		TreatieslawsandregulationsURL: "https://www.canada.ca/en/government/system/laws.html",
		Governmentwidereporting: "Government-wide reporting",
		GovernmentwidereportingURL: "https://www.canada.ca/en/transparency/reporting.html",
		PrimeMinister: "Prime Minister",
		PrimeMinisterURL: "https://pm.gc.ca/eng",
		Howgovernmentworks: "How government works",
		HowgovernmentworksURL: "https://www.canada.ca/en/government/system.html",
		Opengovernment: "Open government",
		OpengovernmentURL: "https://open.canada.ca/en/",
		Aboutthissite: "About this site",
		Topofpage: "Top of page",
		SymboloftheGovernmentofCanada: "Symbol of the Government of Canada",
		Socialmedia: "Social media",
		SocialmediaURL: "https://www.canada.ca/en/social.html",
		Mobileapplications: "Mobile applications",
		MobileapplicationsURL: "https://www.canada.ca/en/mobile.html",
		AboutCanadaca: "About Canada.ca",
		AboutCanadacaURL: "https://www1.canada.ca/en/newsite.html",
		Termsandconditions: "Terms and conditions",
		TermsandconditionsURL: "https://www.canada.ca/en/transparency/terms.html",
		Privacy: "Privacy",
		PrivacyURL: "https://www.canada.ca/en/transparency/privacy.html"
	}
};