// _data/roles.js
module.exports = {
	// canonical keys you'll reference in front matter
	roles: {
		businessAnalysis: { group: "business" },
		contentAuthoring: { group: "author" },
		contentPublishing: { group: "author" },
		uxResearch: { group: "design" },
		uxDesign: { group: "design" },
		visualDesign: { group: "design" },
		frontEndDev: { group: "development" },
		backEndDev: { group: "development" },
		qaAutomated: { group: "testing" },
		qaManual: { group: "testing" },
		productOwnership: { group: "administration" },
		projectManagement: { group: "administration" },
		governance: { group: "administration" },
	},

	// translated labels for roles
	labels: {
		en: {
			businessAnalysis: "Business analysis",
			contentAuthoring: "Content authoring",
			contentPublishing: "Content publishing",
			uxResearch: "User experience research",
			uxDesign: "User experience design",
			visualDesign: "Visual design",
			frontEndDev: "Front-end development",
			backEndDev: "Back-end development",
			qaAutomated: "Automated QA testing",
			qaManual: "Manual QA testing",
			productOwnership: "Product ownership",
			projectManagement: "Project management",
			governance: "Governance",
		},
		fr: {
			businessAnalysis: "Analyse d'affaires",
			contentAuthoring: "Rédaction de contenu",
			contentPublishing: "Publication de contenu",
			uxResearch: "Recherche UX",
			uxDesign: "Conception UX",
			visualDesign: "Conception visuelle",
			frontEndDev: "Développement front-end",
			backEndDev: "Développement back-end",
			qaAutomated: "Tests AQ automatisés",
			qaManual: "Tests AQ manuels",
			productOwnership: "Propriété du produit",
			projectManagement: "Gestion de projet",
			governance: "Gouvernance",
		},
	},

	// translated labels for groups
	groups: {
		en: {
			business: "Business role group",
			author: "Author role group",
			design: "Design role group",
			development: "Development role group",
			testing: "Testing role group",
			administration: "Administration role group",
		},
		fr: {
			business: "Groupe des rôles d'affaires",
			author: "Groupe des rôles d'auteurs",
			design: "Groupe des rôles de conception",
			development: "Groupe des rôles de développement",
			testing: "Groupe des rôles de test",
			administration: "Groupe des rôles administratifs",
		},
	},

	// ARRM role descriptions from W3C WAI
	arrm: {
		en: {
			businessAnalysis: {
				title: "Business Analysis",
				description: "Business analysts are involved in the design or modification of business systems or IT systems. They interact with business stakeholders and subject matter experts in order to understand their problems and needs. They gather, document and analyze business needs and requirements to help steer the team towards an end result that meets the organization's needs and expectations.",
				jobTitles: ["Business Analyst", "Client Sponsor"],
				groupDescription: "Writes business requirements and/or initial user stories, are concerned with ensuring that the project delivers the agreed-upon business benefits."
			},
			contentAuthoring: {
				title: "Content Authoring",
				description: "Content creation is often used in marketing, but can also be a task assigned to a role within a product team. Content creation involves defining a content strategy, the writing or creation of the content or media for a product. The person who authors the content is responsible for making sure that content is accessible to people with disabilities. Content creation extends to roles specific audio and video media production. These begin with the writing of scripts but can extend to the production of the media files or support of live streaming content.",
				keyDeliverables: ["Body copy", "managed content", "scripts", "taxonomies", "writing guidelines", "media files including PDF, audio and video"],
				tasks: ["Content authoring", "media and documentation creation", "content strategies definition"],
				jobTitles: ["Content Strategist", "Content Creator", "Content Designer", "Content Author", "Digital Copywriter", "UX Writer", "Content Producer", "Technical Writer", "Script Writer", "Video Producer", "Podcast Host"],
				groupDescription: "This role includes content strategy and content authoring, including audio/video production. Responsible for creating all text presented by the deliverable in all forms (HTML, audio, video). Defines or selects the standards the content should meet and processes for its review and preparation."
			},
			contentPublishing: {
				title: "Content Publishing",
				description: "Team members who are not front-end web developers that are tasked with preparing content for publishing to websites, products, applications, etc. These team members do not author content, instead they work with the content within specific business enterprise systems or software tools and apply edits to material generated by content authors. Content Publishers may perform some tasks that are a part of the front end web developer skillset, however they are not web developers and are often applying this markup using proprietary tools and widget.",
				keyDeliverables: ["Content editing and formatting", "metadata and SEO optimization", "content publishing schedule", "cross-platform compatibility", "quality assurance and testing"],
				tasks: ["Advanced tagging in a PDF document", "adjusting timing of captions", "creating and editing transcripts", "conversion to ePUB documentation", "applying tags though a proprietary software to generate heading structure", "SSML"],
				jobTitles: ["Content Strategist", "Content Producer", "Content Publisher", "Publishing Technology Specialist", "Content Designer", "Video Editor", "Accessible Materials Specialist", "Information Developer", "Content Developer", "Publishing Implementation Manager"],
				groupDescription: "This role includes content strategy and content authoring, including audio/video production. Responsible for creating all text presented by the deliverable in all forms (HTML, audio, video). Defines or selects the standards the content should meet and processes for its review and preparation."
			},
			uxResearch: {
				title: "User Experience Researcher",
				description: "UX Researchers conduct both exploratory and generative research with end users (e.g. user interviews, ethnographic research, etc.) to gather their feedback. The responsibility of this role is to continuously feed user feedback to those creating products. They test existing concepts and summarize user insights to inform the assets that will be built by the roles in UX Design, Visual Design, Front-end Development and Content Authoring.",
				keyDeliverables: ["Findings from moderated and unmoderated versions of user research studies", "usability testing and user interviews (i.e. a moderator or facilitator was present during the test, or the end user was alone)"],
				tasks: ["Conducting user research with a partial prototype", "concept", "or completed product"],
				jobTitles: ["User Researcher", "UXR (User Experience Researcher)", "Usability Analyst"],
				groupDescription: "This group includes user research, user experience (UX), and presentation decisions. Some roles within this group define the user experience of a product, designing its behaviors and interactions with the end user and/or their assistive technologies. Some roles provide the general \"look and feel\" of the products and features, covering presentation, fonts and colors. Others outline the functionality of features, and their operation through assistive technologies (ATs). They translate input from business roles into user stories, requirements, specifications, documentation, and guidelines used by other roles (mainly Development) to build the finished product. This includes applying user research that has been conducted and an understanding of the intended audiences for a quality experience."
			},
			uxDesign: {
				title: "User Experience Design",
				description: "UX Designers can potentially cover numerous related areas, from conceptualizing the user journey to partial front-end development. For the purposes of this resource, UX Design is defined by its core responsibilities, such as information architecture, creating wireframes (low fidelity screen mockups), and creating prototypes that define interactions.",
				keyDeliverables: ["User journeys", "wireframes", "prototypes", "interaction guidelines", "information architecture"],
				tasks: ["User workflow / process maps", "designing user experiences", "user task and workflow mapping", "creating and maintaining user personas"],
				jobTitles: ["User Experience (UX) Designer", "Product Designer", "Web Designer", "Service Designer"],
				groupDescription: "This group includes user research, user experience (UX), and presentation decisions. Some roles within this group define the user experience of a product, designing its behaviors and interactions with the end user and/or their assistive technologies. Some roles provide the general \"look and feel\" of the products and features, covering presentation, fonts and colors. Others outline the functionality of features, and their operation through assistive technologies (ATs). They translate input from business roles into user stories, requirements, specifications, documentation, and guidelines used by other roles (mainly Development) to build the finished product. This includes applying user research that has been conducted and an understanding of the intended audiences for a quality experience."
			},
			visualDesign: {
				title: "Visual Design",
				description: "Visual Designers focus largely on the look and feel of an product, as an end user would experience it, visually or otherwise. This includes specifying original design of interface elements and layout, choosing fonts and colors, and more. While UX design is focused on how something works, visual design is focused on how it looks and feels.",
				keyDeliverables: ["Style guides", "page comps", "design mockups", "image files"],
				tasks: ["Visual styling", "logos and branding", "animation", "and iconography design"],
				jobTitles: ["Visual Designer", "User Interface (UI) Designer", "Interaction Designer", "Graphic Designer"],
				groupDescription: "This group includes user research, user experience (UX), and presentation decisions. Some roles within this group define the user experience of a product, designing its behaviors and interactions with the end user and/or their assistive technologies. Some roles provide the general \"look and feel\" of the products and features, covering presentation, fonts and colors. Others outline the functionality of features, and their operation through assistive technologies (ATs). They translate input from business roles into user stories, requirements, specifications, documentation, and guidelines used by other roles (mainly Development) to build the finished product. This includes applying user research that has been conducted and an understanding of the intended audiences for a quality experience."
			},
			frontEndDev: {
				title: "Front-End Development",
				description: "Front-end development typically builds the parts of a product that will be interacted with by the user - specifically, the user interface. For the purpose of this resource, front-end development refers to the implementation or codification of the design in functional templates for a product using technologies such as HTML, CSS and JavaScript.",
				keyDeliverables: ["HTML and CSS files", "client-side scripting", "JavaScript libraries and frameworks"],
				tasks: ["Pattern libraries and prototypes", "template functionalities", "semantically-rich HTML document structures and widgets", "use and adapt frameworks and content management systems"],
				jobTitles: ["Front-End Developer", "Web Developer", "Full-Stack Developer", "UI/UX Developer", "JavaScript Developer", "UI/UX Engineer"],
				groupDescription: "Oversees the creation, coding and delivery of the product based upon the requirements provided. Responsible for all user-facing and supporting systems, along with all related infrastructure selection, setup and deployment."
			},
			backEndDev: {
				title: "Back-End Development",
				description: "Back-end developers have a smaller, more indirect involvement with accessibility work, but still play a critical role in delivering accessible products, as the underlying product architecture can inform accessibility solutions. It's important for back-end developers to be involved in accessibility discussions so that any potential issues stemming from how the database is organized can be caught and fixed, or better yet, avoided altogether.",
				jobTitles: ["Back-End Developer", "Middleware Developer", "Database Architect", "Data Engineer"],
				groupDescription: "Oversees the creation, coding and delivery of the product based upon the requirements provided. Responsible for all user-facing and supporting systems, along with all related infrastructure selection, setup and deployment."
			},
			qaAutomated: {
				title: "Automated QA Testing",
				description: "Quality Assurance (QA) automation frameworks typically run against products in order to test features and functionality that would otherwise fall to a manual QA tester. For the purpose of this resource, a QA Tester performing automated tests is responsible for running tests within an automation framework that covers accessibility features and requirements. This can be accomplished either through automation of functional tests, and/or the inclusion of an accessibility testing library within the framework. QA Testers responsible for automated testing may also typically run automated accessibility testing tools, such as browser extensions or add-ons. It is expected that automated tools will uncover about 30 to 35% of potential accessibility issues on a screen. The rest will be identified through the team's manual accessibility testing methodology.",
				jobTitles: ["QA Automation Engineer", "Quality Engineer", "Automation Engineer"],
				groupDescription: "QA Testers run automated test frameworks or manually test products to confirm correct operation based upon provided requirement. Quality Assurance (QA) Testers typically don't contribute directly to the design and development phases of a product. They may have the opportunity to review and sign off on designs before they are implemented. The main accessibility role of a QA Tester in the accessibility lifecycle is to understand the accessibility requirements that exist and to run tests to ensure the product or feature conforms to those requirements. The testing roles have been split between automated and manual, but a number of QA professionals will do both."
			},
			qaManual: {
				title: "Manual QA Testing",
				description: "Quality Assurance Testers responsible for manual testing will typically handle the testing that cannot be covered through the use of automated tools. They will typically be resources that are more knowledgeable about accessibility, with a deeper understanding of the requirements, and some experience operating assistive technologies for testing, such as screen readers. They will typically run a series of test cases to validate the degree of inclusion of the components of a screen and will be charged with making sure that the overall user experience is positive for people with disabilities. It is expected that manual testing will build on top of an automated testing process, in order to cover the remaining 65 to 70% of potential accessibility issues on any given screen.",
				jobTitles: ["QA Analyst", "QA Specialist", "User Acceptance Tester", "Functional Tester"],
				groupDescription: "QA Testers run automated test frameworks or manually test products to confirm correct operation based upon provided requirement. Quality Assurance (QA) Testers typically don't contribute directly to the design and development phases of a product. They may have the opportunity to review and sign off on designs before they are implemented. The main accessibility role of a QA Tester in the accessibility lifecycle is to understand the accessibility requirements that exist and to run tests to ensure the product or feature conforms to those requirements. The testing roles have been split between automated and manual, but a number of QA professionals will do both."
			},
			productOwnership: {
				title: "Product Ownership",
				description: "Product owners own individual products and define their features and are key to defining the importance of accessibility on a project. It is their job to make sure that products are built and delivered in a way that meets business needs and user needs. They should have some basic understanding of the accessibility implications of the UI requirements they request, such as cost and required infrastructure. But, as with features in general, they delegate design and implementation decisions to other roles. As a result, they are typically not directly involved and do not have ownership in the ARRM model.",
				jobTitles: ["Product Manager", "Product Owner", "Release Manager", "Business Owner"],
				groupDescription: "The roles in this section cover managing the product and project, as well as other bureaucratic functions of the broader organization that often have a larger mandate than any individual project. Most administrative roles, as defined in this resource, have very little, if anything, to do with the design, the implementation, or the testing of accessibility principles to create more inclusive applications and websites. These roles, however, are still instrumental in ensuring that the team members who are actively taking part in making content accessible and conformant with WCAG can be successful at doing so. This begins with project managers and product owners working hand in hand with the design, development and testing teams, but also other governance roles contributing to steering the organization's culture in a direction that is aligned with the goals pursued by accessibility guidelines."
			},
			projectManagement: {
				title: "Project Management",
				description: "Project managers are primarily responsible for keeping everything about the process of building a product organized and on track. They have little decision-making power directly impacting accessibility. The person managing the project should make sure that accessibility is built into estimates, user stories (if Agile), and requirements documents. In smaller teams, the roles of product owners and project managers often overlap.",
				jobTitles: ["Project Manager", "Scrum Master (Agile)", "Team Lead"],
				groupDescription: "The roles in this section cover managing the product and project, as well as other bureaucratic functions of the broader organization that often have a larger mandate than any individual project. Most administrative roles, as defined in this resource, have very little, if anything, to do with the design, the implementation, or the testing of accessibility principles to create more inclusive applications and websites. These roles, however, are still instrumental in ensuring that the team members who are actively taking part in making content accessible and conformant with WCAG can be successful at doing so. This begins with project managers and product owners working hand in hand with the design, development and testing teams, but also other governance roles contributing to steering the organization's culture in a direction that is aligned with the goals pursued by accessibility guidelines."
			},
			governance: {
				title: "Governance",
				description: "Unlike most other administrative roles, governance is not part of an individual project team. Their mandate focuses on the big picture, often enterprise-wide initiatives. Most importantly to individual projects, governance roles are deliberative (often committee-based) and are not bound to the deadlines of a singular project without outside, executive influence to encourage higher-velocity decision making.",
				jobTitles: ["Legal", "procurement", "conformance", "administrative", "governance", "branding"],
				groupDescription: "The roles in this section cover managing the product and project, as well as other bureaucratic functions of the broader organization that often have a larger mandate than any individual project. Most administrative roles, as defined in this resource, have very little, if anything, to do with the design, the implementation, or the testing of accessibility principles to create more inclusive applications and websites. These roles, however, are still instrumental in ensuring that the team members who are actively taking part in making content accessible and conformant with WCAG can be successful at doing so. This begins with project managers and product owners working hand in hand with the design, development and testing teams, but also other governance roles contributing to steering the organization's culture in a direction that is aligned with the goals pursued by accessibility guidelines."
			}
		},
		fr: {
			businessAnalysis: {
				title: "Analyse d'affaires",
				description: "Les analystes d'affaires participent à la conception ou à la modification de systèmes d'affaires ou de systèmes informatiques. Ils interagissent avec les parties prenantes et les experts en la matière afin de comprendre leurs problèmes et leurs besoins. Ils recueillent, documentent et analysent les besoins et exigences d'affaires pour aider à orienter l'équipe vers un résultat final qui répond aux besoins et attentes de l'organisation.",
				jobTitles: ["Analyste d'affaires", "Commanditaire client"],
				groupDescription: "Rédige les exigences d'affaires et/ou les récits utilisateur initiaux, s'assure que le projet livre les bénéfices d'affaires convenus."
			},
			contentAuthoring: {
				title: "Rédaction de contenu",
				description: "La création de contenu est souvent utilisée en marketing, mais peut aussi être une tâche assignée à un rôle au sein d'une équipe de produit. La création de contenu implique la définition d'une stratégie de contenu, la rédaction ou la création du contenu ou des médias pour un produit. La personne qui rédige le contenu est responsable de s'assurer que le contenu est accessible aux personnes handicapées. La création de contenu s'étend aux rôles spécifiques de production de médias audio et vidéo. Celles-ci commencent par la rédaction de scripts mais peuvent s'étendre à la production des fichiers multimédias ou au support de contenu de diffusion en direct.",
				keyDeliverables: ["Texte de base", "contenu géré", "scripts", "taxonomies", "directives de rédaction", "fichiers multimédias incluant PDF, audio et vidéo"],
				tasks: ["Rédaction de contenu", "création de médias et de documentation", "définition de stratégies de contenu"],
				jobTitles: ["Stratège de contenu", "Créateur de contenu", "Concepteur de contenu", "Auteur de contenu", "Rédacteur numérique", "Rédacteur UX", "Producteur de contenu", "Rédacteur technique", "Scénariste", "Producteur vidéo", "Animateur de podcast"],
				groupDescription: "Ce rôle inclut la stratégie de contenu et la création de contenu, incluant la production audio/vidéo. Responsable de créer tout le texte présenté par le livrable sous toutes les formes (HTML, audio, vidéo). Définit ou sélectionne les normes que le contenu doit respecter et les processus pour sa révision et préparation."
			},
			contentPublishing: {
				title: "Publication de contenu",
				description: "Membres d'équipe qui ne sont pas des développeurs web front-end et qui sont chargés de préparer le contenu pour la publication sur des sites web, produits, applications, etc. Ces membres d'équipe ne créent pas de contenu, ils travaillent plutôt avec le contenu dans des systèmes d'entreprise spécifiques ou des outils logiciels et appliquent des modifications au matériel généré par les auteurs de contenu. Les éditeurs de contenu peuvent effectuer certaines tâches qui font partie de l'ensemble de compétences du développeur web front-end, cependant ils ne sont pas des développeurs web et appliquent souvent cette balisage en utilisant des outils propriétaires et des widgets.",
				keyDeliverables: ["Édition et formatage de contenu", "optimisation des métadonnées et SEO", "calendrier de publication de contenu", "compatibilité multiplateforme", "assurance qualité et tests"],
				tasks: ["Balisage avancé dans un document PDF", "ajustement du timing des sous-titres", "création et édition de transcriptions", "conversion vers la documentation ePUB", "application de balises via un logiciel propriétaire pour générer une structure d'en-têtes", "SSML"],
				jobTitles: ["Stratège de contenu", "Producteur de contenu", "Éditeur de contenu", "Spécialiste en technologie de publication", "Concepteur de contenu", "Éditeur vidéo", "Spécialiste en matériaux accessibles", "Développeur d'information", "Développeur de contenu", "Gestionnaire d'implémentation de publication"],
				groupDescription: "Ce rôle inclut la stratégie de contenu et la création de contenu, incluant la production audio/vidéo. Responsable de créer tout le texte présenté par le livrable sous toutes les formes (HTML, audio, vidéo). Définit ou sélectionne les normes que le contenu doit respecter et les processus pour sa révision et préparation."
			},
			uxResearch: {
				title: "Recherche d'expérience utilisateur",
				description: "Les chercheurs UX mènent des recherches exploratoires et génératives avec les utilisateurs finaux (par exemple, entretiens utilisateur, recherche ethnographique, etc.) pour recueillir leurs commentaires. La responsabilité de ce rôle est de fournir continuellement les commentaires des utilisateurs à ceux qui créent les produits. Ils testent les concepts existants et résument les insights utilisateur pour informer les actifs qui seront construits par les rôles en conception UX, conception visuelle, développement front-end et création de contenu.",
				keyDeliverables: ["Résultats d'études de recherche utilisateur modérées et non modérées", "tests d'utilisabilité et entretiens utilisateur (c'est-à-dire qu'un modérateur ou facilitateur était présent pendant le test, ou l'utilisateur final était seul)"],
				tasks: ["Mener des recherches utilisateur avec un prototype partiel", "concept", "ou produit terminé"],
				jobTitles: ["Chercheur utilisateur", "UXR (Chercheur d'expérience utilisateur)", "Analyste d'utilisabilité"],
				groupDescription: "Ce groupe inclut la recherche utilisateur, l'expérience utilisateur (UX), et les décisions de présentation. Certains rôles de ce groupe définissent l'expérience utilisateur d'un produit, concevant ses comportements et interactions avec l'utilisateur final et/ou leurs technologies d'assistance. Certains rôles fournissent l'apparence générale des produits et fonctionnalités, couvrant la présentation, les polices et couleurs. D'autres décrivent la fonctionnalité des caractéristiques, et leur fonctionnement à travers les technologies d'assistance (TA). Ils traduisent les entrées des rôles d'affaires en récits utilisateur, exigences, spécifications, documentation et directives utilisées par d'autres rôles (principalement le développement) pour construire le produit fini. Cela inclut l'application de recherche utilisateur qui a été menée et une compréhension des audiences visées pour une expérience de qualité."
			},
			uxDesign: {
				title: "Conception d'expérience utilisateur",
				description: "Les concepteurs UX peuvent potentiellement couvrir de nombreux domaines connexes, de la conceptualisation du parcours utilisateur au développement front-end partiel. Aux fins de cette ressource, la conception UX est définie par ses responsabilités principales, telles que l'architecture de l'information, la création de wireframes (maquettes d'écran de faible fidélité), et la création de prototypes qui définissent les interactions.",
				keyDeliverables: ["Parcours utilisateur", "wireframes", "prototypes", "directives d'interaction", "architecture de l'information"],
				tasks: ["Cartes de flux de travail / processus utilisateur", "conception d'expériences utilisateur", "cartographie des tâches et flux de travail utilisateur", "création et maintenance de personas utilisateur"],
				jobTitles: ["Concepteur d'expérience utilisateur (UX)", "Concepteur de produit", "Concepteur web", "Concepteur de service"],
				groupDescription: "Ce groupe inclut la recherche utilisateur, l'expérience utilisateur (UX), et les décisions de présentation. Certains rôles de ce groupe définissent l'expérience utilisateur d'un produit, concevant ses comportements et interactions avec l'utilisateur final et/ou leurs technologies d'assistance. Certains rôles fournissent l'apparence générale des produits et fonctionnalités, couvrant la présentation, les polices et couleurs. D'autres décrivent la fonctionnalité des caractéristiques, et leur fonctionnement à travers les technologies d'assistance (TA). Ils traduisent les entrées des rôles d'affaires en récits utilisateur, exigences, spécifications, documentation et directives utilisées par d'autres rôles (principalement le développement) pour construire le produit fini. Cela inclut l'application de recherche utilisateur qui a été menée et une compréhension des audiences visées pour une expérience de qualité."
			},
			visualDesign: {
				title: "Conception visuelle",
				description: "Les concepteurs visuels se concentrent largement sur l'apparence et la sensation d'un produit, tel qu'un utilisateur final l'expérimenterait, visuellement ou autrement. Cela inclut la spécification de la conception originale des éléments d'interface et de la mise en page, le choix des polices et couleurs, et plus encore. Alors que la conception UX se concentre sur comment quelque chose fonctionne, la conception visuelle se concentre sur comment cela apparaît et se ressent.",
				keyDeliverables: ["Guides de style", "compositions de page", "maquettes de conception", "fichiers d'image"],
				tasks: ["Style visuel", "logos et image de marque", "animation", "et conception d'iconographie"],
				jobTitles: ["Concepteur visuel", "Concepteur d'interface utilisateur (UI)", "Concepteur d'interaction", "Graphiste"],
				groupDescription: "Ce groupe inclut la recherche utilisateur, l'expérience utilisateur (UX), et les décisions de présentation. Certains rôles de ce groupe définissent l'expérience utilisateur d'un produit, concevant ses comportements et interactions avec l'utilisateur final et/ou leurs technologies d'assistance. Certains rôles fournissent l'apparence générale des produits et fonctionnalités, couvrant la présentation, les polices et couleurs. D'autres décrivent la fonctionnalité des caractéristiques, et leur fonctionnement à travers les technologies d'assistance (TA). Ils traduisent les entrées des rôles d'affaires en récits utilisateur, exigences, spécifications, documentation et directives utilisées par d'autres rôles (principalement le développement) pour construire le produit fini. Cela inclut l'application de recherche utilisateur qui a été menée et une compréhension des audiences visées pour une expérience de qualité."
			},
			frontEndDev: {
				title: "Développement front-end",
				description: "Le développement front-end construit typiquement les parties d'un produit qui seront interagies par l'utilisateur - spécifiquement, l'interface utilisateur. Aux fins de cette ressource, le développement front-end fait référence à l'implémentation ou codification de la conception en modèles fonctionnels pour un produit utilisant des technologies telles que HTML, CSS et JavaScript.",
				keyDeliverables: ["Fichiers HTML et CSS", "scripts côté client", "bibliothèques et frameworks JavaScript"],
				tasks: ["Bibliothèques de modèles et prototypes", "fonctionnalités de modèles", "structures de documents HTML et widgets sémantiquement riches", "utiliser et adapter des frameworks et systèmes de gestion de contenu"],
				jobTitles: ["Développeur front-end", "Développeur web", "Développeur full-stack", "Développeur UI/UX", "Développeur JavaScript", "Ingénieur UI/UX"],
				groupDescription: "Supervise la création, le codage et la livraison du produit basé sur les exigences fournies. Responsable de tous les systèmes orientés utilisateur et de support, ainsi que de toute la sélection, configuration et déploiement d'infrastructure connexe."
			},
			backEndDev: {
				title: "Développement back-end",
				description: "Les développeurs back-end ont une implication plus petite et plus indirecte avec le travail d'accessibilité, mais jouent toujours un rôle critique dans la livraison de produits accessibles, car l'architecture de produit sous-jacente peut informer les solutions d'accessibilité. Il est important que les développeurs back-end soient impliqués dans les discussions d'accessibilité afin que tout problème potentiel découlant de la façon dont la base de données est organisée puisse être attrapé et corrigé, ou mieux encore, évité complètement.",
				jobTitles: ["Développeur back-end", "Développeur middleware", "Architecte de base de données", "Ingénieur de données"],
				groupDescription: "Supervise la création, le codage et la livraison du produit basé sur les exigences fournies. Responsable de tous les systèmes orientés utilisateur et de support, ainsi que de toute la sélection, configuration et déploiement d'infrastructure connexe."
			},
			qaAutomated: {
				title: "Tests AQ automatisés",
				description: "Les frameworks d'automatisation d'assurance qualité (AQ) s'exécutent typiquement contre les produits afin de tester les fonctionnalités et la fonctionnalité qui autrement incomberaient à un testeur AQ manuel. Aux fins de cette ressource, un testeur AQ effectuant des tests automatisés est responsable d'exécuter des tests dans un framework d'automatisation qui couvre les fonctionnalités et exigences d'accessibilité. Ceci peut être accompli soit par l'automatisation de tests fonctionnels, et/ou l'inclusion d'une bibliothèque de tests d'accessibilité dans le framework. Les testeurs AQ responsables des tests automatisés peuvent aussi typiquement exécuter des outils de tests d'accessibilité automatisés, tels que des extensions de navigateur ou des modules complémentaires. Il est attendu que les outils automatisés découvriront environ 30 à 35% des problèmes d'accessibilité potentiels sur un écran. Le reste sera identifié à travers la méthodologie de tests d'accessibilité manuels de l'équipe.",
				jobTitles: ["Ingénieur d'automatisation AQ", "Ingénieur qualité", "Ingénieur d'automatisation"],
				groupDescription: "Les testeurs AQ exécutent des frameworks de tests automatisés ou testent manuellement les produits pour confirmer le fonctionnement correct basé sur les exigences fournies. Les testeurs d'assurance qualité (AQ) ne contribuent typiquement pas directement aux phases de conception et développement d'un produit. Ils peuvent avoir l'opportunité de réviser et approuver les conceptions avant qu'elles soient implémentées. Le rôle principal d'accessibilité d'un testeur AQ dans le cycle de vie d'accessibilité est de comprendre les exigences d'accessibilité qui existent et d'exécuter des tests pour s'assurer que le produit ou la fonctionnalité se conforme à ces exigences. Les rôles de test ont été divisés entre automatisé et manuel, mais un nombre de professionnels AQ feront les deux."
			},
			qaManual: {
				title: "Tests AQ manuels",
				description: "Les testeurs d'assurance qualité responsables des tests manuels géreront typiquement les tests qui ne peuvent pas être couverts par l'utilisation d'outils automatisés. Ils seront typiquement des ressources qui sont plus connaissantes sur l'accessibilité, avec une compréhension plus profonde des exigences, et une certaine expérience d'utilisation des technologies d'assistance pour les tests, telles que les lecteurs d'écran. Ils exécuteront typiquement une série de cas de test pour valider le degré d'inclusion des composants d'un écran et seront chargés de s'assurer que l'expérience utilisateur globale est positive pour les personnes handicapées. Il est attendu que les tests manuels s'appuieront sur un processus de tests automatisés, afin de couvrir les 65 à 70% restants des problèmes d'accessibilité potentiels sur tout écran donné.",
				jobTitles: ["Analyste AQ", "Spécialiste AQ", "Testeur d'acceptation utilisateur", "Testeur fonctionnel"],
				groupDescription: "Les testeurs AQ exécutent des frameworks de tests automatisés ou testent manuellement les produits pour confirmer le fonctionnement correct basé sur les exigences fournies. Les testeurs d'assurance qualité (AQ) ne contribuent typiquement pas directement aux phases de conception et développement d'un produit. Ils peuvent avoir l'opportunité de réviser et approuver les conceptions avant qu'elles soient implémentées. Le rôle principal d'accessibilité d'un testeur AQ dans le cycle de vie d'accessibilité est de comprendre les exigences d'accessibilité qui existent et d'exécuter des tests pour s'assurer que le produit ou la fonctionnalité se conforme à ces exigences. Les rôles de test ont été divisés entre automatisé et manuel, mais un nombre de professionnels AQ feront les deux."
			},
			productOwnership: {
				title: "Propriété du produit",
				description: "Les propriétaires de produit possèdent des produits individuels et définissent leurs fonctionnalités et sont clés pour définir l'importance de l'accessibilité sur un projet. C'est leur travail de s'assurer que les produits sont construits et livrés d'une manière qui répond aux besoins d'affaires et aux besoins des utilisateurs. Ils devraient avoir une certaine compréhension de base des implications d'accessibilité des exigences UI qu'ils demandent, telles que le coût et l'infrastructure requise. Mais, comme avec les fonctionnalités en général, ils délèguent les décisions de conception et d'implémentation à d'autres rôles. En conséquence, ils ne sont typiquement pas directement impliqués et n'ont pas de propriété dans le modèle ARRM.",
				jobTitles: ["Gestionnaire de produit", "Propriétaire de produit", "Gestionnaire de version", "Propriétaire d'affaires"],
				groupDescription: "Les rôles de cette section couvrent la gestion du produit et du projet, ainsi que d'autres fonctions bureaucratiques de l'organisation plus large qui ont souvent un mandat plus large que tout projet individuel. La plupart des rôles administratifs, tels que définis dans cette ressource, ont très peu, voire rien, à voir avec la conception, l'implémentation, ou les tests des principes d'accessibilité pour créer des applications et sites web plus inclusifs. Ces rôles, cependant, sont toujours instrumentaux pour s'assurer que les membres d'équipe qui participent activement à rendre le contenu accessible et conforme aux WCAG peuvent réussir à le faire. Cela commence avec les gestionnaires de projet et propriétaires de produit travaillant main dans la main avec les équipes de conception, développement et test, mais aussi d'autres rôles de gouvernance contribuant à orienter la culture de l'organisation dans une direction qui est alignée avec les objectifs poursuivis par les directives d'accessibilité."
			},
			projectManagement: {
				title: "Gestion de projet",
				description: "Les gestionnaires de projet sont principalement responsables de maintenir tout ce qui concerne le processus de construction d'un produit organisé et sur la bonne voie. Ils ont peu de pouvoir décisionnel impactant directement l'accessibilité. La personne gérant le projet devrait s'assurer que l'accessibilité est intégrée dans les estimations, les récits utilisateur (si Agile), et les documents d'exigences. Dans les petites équipes, les rôles de propriétaires de produit et gestionnaires de projet se chevauchent souvent.",
				jobTitles: ["Gestionnaire de projet", "Scrum Master (Agile)", "Chef d'équipe"],
				groupDescription: "Les rôles de cette section couvrent la gestion du produit et du projet, ainsi que d'autres fonctions bureaucratiques de l'organisation plus large qui ont souvent un mandat plus large que tout projet individuel. La plupart des rôles administratifs, tels que définis dans cette ressource, ont très peu, voire rien, à voir avec la conception, l'implémentation, ou les tests des principes d'accessibilité pour créer des applications et sites web plus inclusifs. Ces rôles, cependant, sont toujours instrumentaux pour s'assurer que les membres d'équipe qui participent activement à rendre le contenu accessible et conforme aux WCAG peuvent réussir à le faire. Cela commence avec les gestionnaires de projet et propriétaires de produit travaillant main dans la main avec les équipes de conception, développement et test, mais aussi d'autres rôles de gouvernance contribuant à orienter la culture de l'organisation dans une direction qui est alignée avec les objectifs poursuivis par les directives d'accessibilité."
			},
			governance: {
				title: "Gouvernance",
				description: "Contrairement à la plupart des autres rôles administratifs, la gouvernance ne fait pas partie d'une équipe de projet individuelle. Leur mandat se concentre sur la vue d'ensemble, souvent des initiatives à l'échelle de l'entreprise. Plus important pour les projets individuels, les rôles de gouvernance sont délibératifs (souvent basés sur des comités) et ne sont pas liés aux échéances d'un projet singulier sans influence exécutive extérieure pour encourager une prise de décision à plus haute vélocité.",
				jobTitles: ["Juridique", "approvisionnement", "conformité", "administratif", "gouvernance", "image de marque"],
				groupDescription: "Les rôles de cette section couvrent la gestion du produit et du projet, ainsi que d'autres fonctions bureaucratiques de l'organisation plus large qui ont souvent un mandat plus large que tout projet individuel. La plupart des rôles administratifs, tels que définis dans cette ressource, ont très peu, voire rien, à voir avec la conception, l'implémentation, ou les tests des principes d'accessibilité pour créer des applications et sites web plus inclusifs. Ces rôles, cependant, sont toujours instrumentaux pour s'assurer que les membres d'équipe qui participent activement à rendre le contenu accessible et conforme aux WCAG peuvent réussir à le faire. Cela commence avec les gestionnaires de projet et propriétaires de produit travaillant main dans la main avec les équipes de conception, développement et test, mais aussi d'autres rôles de gouvernance contribuant à orienter la culture de l'organisation dans une direction qui est alignée avec les objectifs poursuivis par les directives d'accessibilité."
			}
		}
	},

	// detailed descriptions for groups
	descriptions: {
		en: {
			business: "Business analysts and stakeholders who define requirements, conduct user research, and ensure digital products meet accessibility standards from a strategic perspective.",
			author: "Content creators, writers, and publishers responsible for creating accessible content, including proper document structure, alternative text, and clear language.",
			design: "User experience designers, visual designers, and researchers who create inclusive designs, conduct accessibility testing, and ensure usable interfaces for all users.",
			development: "Front-end and back-end developers who implement accessible code, integrate assistive technologies, and build inclusive digital experiences.",
			testing: "Quality assurance professionals who test for accessibility compliance, conduct automated and manual testing, and ensure products meet WCAG standards.",
			administration: "Project managers, product owners, and governance teams who oversee accessibility strategy, ensure compliance, and manage accessibility initiatives.",
		},
		fr: {
			business: "Analystes d'affaires et parties prenantes qui définissent les exigences, mènent des recherches utilisateur et s'assurent que les produits numériques respectent les normes d'accessibilité d'un point de vue stratégique.",
			author: "Créateurs de contenu, rédacteurs et éditeurs responsables de créer du contenu accessible, incluant une structure de document appropriée, du texte alternatif et un langage clair.",
			design: "Concepteurs d'expérience utilisateur, concepteurs visuels et chercheurs qui créent des conceptions inclusives, effectuent des tests d'accessibilité et garantissent des interfaces utilisables pour tous.",
			development: "Développeurs front-end et back-end qui implémentent du code accessible, intègrent les technologies d'assistance et construisent des expériences numériques inclusives.",
			testing: "Professionnels de l'assurance qualité qui testent la conformité à l'accessibilité, effectuent des tests automatisés et manuels, et s'assurent que les produits respectent les normes WCAG.",
			administration: "Gestionnaires de projet, propriétaires de produit et équipes de gouvernance qui supervisent la stratégie d'accessibilité, assurent la conformité et gèrent les initiatives d'accessibilité.",
		},
	},
};
