module.exports = {
	fr: {
		accessibilityFundamentals: "Principes de base de l’accessibilité",
		aboutDisabilities: "À propos des handicaps",
		globalAccessibilityStandards: "Normes d’accessibilité mondiales",
		howTos: "Comment faire",
		createDocument: "Créer un document",
		createEmails: "Créer un courriel",
		createForms: "Créer un formulaire",
		createWebContent: "Créer du contenu Web",
		designCourse: "Concevoir un cours",
		hostMeetingsAndEvents: "Organiser des réunions et des événements",
		testYourProducts: "Testez vos produits",
		resourcesAndTools: "Ressources et outils",
		resources: "Ressources",
		tools: "Outils",
		learningAndDevelopment: "Apprentissage et perfectionnement",
		accessibilityInTheGovernmentOfCanada:
			"Accessibilité au gouvernement du Canada",
		accessibilityAct: "Loi sur l’accessibilité",
		procurement: "Approvisionnement",
		accessibilityStandards: "Normes d’accessibilité",
		communityDirectory: "Répertoire de la communauté",
		aboutUs: "À propos de nous",
		aboutTheDigitalTheAccessibilityToolkitProject: "À propos du projet",
		contactUs: "Contactez-nous",
		accessibilityInYourRole: "L'accessibilité dans votre rôle",
	},

	en: {
		accessibilityFundamentals: "Accessibility Fundamentals",
		aboutDisabilities: "About Disabilities",
		globalAccessibilityStandards: "Global Accessibility Standards",
		howTos: "How to’s",
		createDocument: "Create document",
		createEmails: "Create emails",
		createForms: "Create forms",
		createWebContent: "Create web content",
		designCourse: "Design a course",
		hostMeetingsAndEvents: "Host a meetings and events",
		testYourProducts: "Test your products",
		resourcesAndTools: "Resources and Tools",
		resources: "Resources",
		tools: "Tools",
		learningAndDevelopment: "Learning and Development",
		accessibilityInTheGovernmentOfCanada:
			"Accessibility in the Government of Canada",
		accessibilityAct: "Accessibility Act",
		procurement: "Procurement",
		accessibilityStandards: "Accessibility standards",
		communityDirectory: "Community Directory",
		aboutUs: "About Us",
		aboutTheDigitalTheAccessibilityToolkitProject:
			"About the Digital the accessibility toolkit project",
		contactUs: "Contact us",
		accessibilityInYourRole: "Accessibility in your role",
	},
};
