module.exports = {
	tags: {
		fr: {
			aboutDisabilities: "À propos des handicaps",
			globalAccessibilityStandards: "Normes d’accessibilité mondiales",
			createDocument: "Créer un document",
			createEmails: "Créer un courriel",
			createForms: "Créer un formulaire",
			createWebContent: "Créer du contenu Web",
			designCourse: "Concevoir un cours",
			designingAccessible: "Concevoir l'accessibilité",
			hostMeetingsAndEvents: "Organiser des réunions et des événements",
			testYourProducts: "Testez vos produits",
			resources: "Ressources",
			tools: "Outils",
			accessibilityAct: "Loi sur l’accessibilité",
			procurement: "Approvisionnement",
			accessibilityStandards: "Normes d’accessibilité",
			communityDirectory: "Répertoire de la communauté",
			aboutTheDigitalTheAccessibilityToolkitProject: "À propos du projet",
			contactUs: "Contactez-nous",
			accessibilityInYourRole: "L'accessibilité dans votre rôle",
			mainAbout: "Section à propos de nous sur la page d'accueil",
			office2016: "Comment créer des documents accessibles dans Office 2016",
			office365: "Comment créer des documents accessibles dans Office 365",
		},
		en: {
			aboutDisabilities: "About Disabilities",
			globalAccessibilityStandards: "Global Accessibility Standards",
			createDocument: "Create document",
			createEmails: "Create emails",
			createForms: "Create forms",
			createWebContent: "Create web content",
			designCourse: "Design a course",
			designingAccessible: "Designing Accessibility",
			hostMeetingsAndEvents: "Host a meetings and events",
			testYourProducts: "Test your products",
			resources: "Resources",
			tools: "Tools",
			accessibilityAct: "Accessibility Act",
			procurement: "Procurement",
			accessibilityStandards: "Accessibility standards",
			communityDirectory: "Community Directory",
			aboutTheDigitalTheAccessibilityToolkitProject:
				"About the Digital the accessibility toolkit project",
			contactUs: "Contact us",
			accessibilityInYourRole: "Accessibility in your role",
			mainAbout: "About us section on homepage",
			office2016: "How to create accessible documents in Office 2016",
			office365: "How to create accessible documents in Office 365",
		},
	},
	subjects: {
		fr: {
			accessibilityFundamentals: "Principes de base de l’accessibilité",
			howTos: "Comment faire",
			resourcesAndTools: "Ressources et outils",
			learningAndDevelopment: "Apprentissage et perfectionnement",
			accessibilityInTheGovernmentOfCanada:
				"Accessibilité au gouvernement du Canada",
			aboutUs: "À propos de nous",
		},
		en: {
			accessibilityFundamentals: "Accessibility Fundamentals",
			howTos: "How to’s",
			resourcesAndTools: "Resources and Tools",
			learningAndDevelopment: "Learning and Development",
			accessibilityInTheGovernmentOfCanada:
				"Accessibility in the Government of Canada",
			aboutUs: "About Us",
		},
	},
};
