module.exports = {
	tags: {
		fr: {
			aboutDisabilities: "Types de handicap les plus courants",
			globalAccessibilityStandards: "Normes d’accessibilité mondiales",
			createDocument: "Créer un document",
			createEmails: "Créer un courriel",
			createForms: "Créer un formulaire",
			createWebContent: "Créer du contenu web",
			designCourse: "Concevoir un cours",
			designingAccessible:
				"Principes de conception pour des services accessibles",
			accessibleVirtualEvents: "Événements virtuels accessibles",
			testYourProducts: "Testez vos produits",
			accessibilityAct: "Loi sur l’accessibilité",
			procurement: "Approvisionnement",
			accessibilityStandards: "Normes d’accessibilité",
			communityDirectory: "Répertoire de la communauté",
			aboutTheDigitalTheAccessibilityToolkitProject: "À propos du projet",
			contactUs: "Contactez-nous",
			accessibilityInYourRole: "L'accessibilité dans votre rôle",
			mainAbout: "Section à propos de nous sur la page d'accueil",
			msTips : "Fiches de conseils pour Microsoft Office",
			office2016:
				"Comment créer des documents accessibles dans Office 2016",
			microsoft365:
				"Comment créer des documents accessibles dans Microsoft 365",
		},
		en: {
			aboutDisabilities: "Most common types of disability",
			globalAccessibilityStandards: "Global accessibility standards",
			createDocument: "Create document",
			createEmails: "Create emails",
			createForms: "Create forms",
			createWebContent: "Create web content",
			designCourse: "Design a course",
			designingAccessible: "Designing accessible services",
			accessibleVirtualEvents: "Accessible virtual events",
			testYourProducts: "Test your products",
			accessibilityAct: "Accessibility act",
			procurement: "Procurement",
			accessibilityStandards: "Accessibility standards",
			communityDirectory: "Community directory",
			aboutTheDigitalTheAccessibilityToolkitProject:
				"About the Digital the Accessibility Toolkit project",
			contactUs: "Contact us",
			accessibilityInYourRole: "Accessibility in your role",
			mainAbout: "About us section on homepage",
			office2016: "How to create accessible documents in Office 2016",
			msTips: "Tip sheets for Microsoft Office",
			microsoft365: "How to create accessible documents in Microsoft 365",
		},
	},
	subjects: {
		fr: {
			accessibilityFundamentals: "Principes de base de l’accessibilité",
			howTos: "Comment faire",
			resourcesAndTools: "Ressources et outils",
			learningAndDevelopment: "Apprentissage et perfectionnement",
			accessibilityInTheGovernmentOfCanada:
				"Accessibilité numérique au gouvernement du Canada",
			aboutUs: "À propos de nous",
			roles: "Accessibilité dans votre rôle",
		},
		en: {
			accessibilityFundamentals: "Accessibility fundamentals",
			howTos: "How-tos",
			resourcesAndTools: "Resources and tools",
			learningAndDevelopment: "Learning and development",
			accessibilityInTheGovernmentOfCanada:
				"Digital accessibility in the Government of Canada",
			aboutUs: "About us",
			roles: "Accessibility in your role",
		},
	},
};
